### ISSUE TITLE
null-ls not matches the editorconfig-checker installed by mason

### ISSUE THREAD

**Issue by adoyle-h** [mason-org/mason-registry#331]
Hi, I'm using [null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim) and [editorconfig-checker](https://github.com/editorconfig-checker/editorconfig-checker).

I find that null-ls uses the command [`ec`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/33cfeb7a761f08e8535dca722d4b237cabadd371/lua/null-ls/builtins/diagnostics/editorconfig_checker.lua#L15), while mason-registry install this package to [`editorconfig-checker`](https://github.com/mason-org/mason-registry/blob/d88b48940d2a4dc80a866123b02816b72c0afa4c/packages/editorconfig-checker/package.yaml#L36). So null-ls will not find the available `ec` command.

Should we fix the issue in either mason-registry or null-ls?

Or mason-registry add one line like below?

```yaml
bin:
  editorconfig-checker: "bin/{{ source.asset.file | strip_suffix '.tar.gz' }}"
  ec: "bin/{{ source.asset.file | strip_suffix '.tar.gz' }}"
```
