### ISSUE TITLE
missing dmypy symlink

### ISSUE THREAD

**Issue by shimeoki** [mason-org/mason-registry#9498]
[mypy/package.yaml](https://github.com/mason-org/mason-registry/blob/dbb0027cee4c06a1cac6566ddc614f9698b86228/packages/mypy/package.yaml) contains several executable such as `mypy`, `dmypy` and `mypyc`, but the package files uses only one:

https://github.com/mason-org/mason-registry/blob/dbb0027cee4c06a1cac6566ddc614f9698b86228/packages/mypy/package.yaml#L16C1-L17C18

it breaks, for example, [nvim-lint](https://github.com/mfussenegger/nvim-lint), because the plugin has the configuration for `dmypy` and the corresponding binary isn't linked. it works if i create the symlink by hand.

i would have submitted a pr, if i knew how to fix this. my intuition tells me that

```yaml
bin:
  mypy: pypi:mypy
  dmypy: pypi:dmypy
```

can work, but `dmypy` is not in a separate `pypi` package, and is a part of `mypy` package, so maybe something like

```yaml
bin:
  mypy: pypi:mypy
  dmypy: pypi:mypy.dmypy
```

works?
